const TermsOfUse = () => {
  return (
    <div className="container p-8 border my-7 w-[22rem] sm:w-2/3 mx-auto rounded-xl">
      <h1 className="text-3xl font-bold mb-4">
        Terms of Use - Merge JSON Files
      </h1>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-2">1. Acceptance of Terms</h2>
        <p className="text-gray-700">
          By accessing and using{" "}
          <span className="font-semibold">merge-json-files.com</span>, including
          its JSON processing tools (JSON merger and JSON splitter), you agree
          to be bound by these Terms of Use. If you do not agree to these terms,
          please do not use the Website.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-2">3. User Obligations</h2>
        <h3 className="text-xl font-semibold mb-2 mt-4">3.1 Acceptable Use</h3>
        <p className="text-gray-700">
          You agree to use the Website and its tools in accordance with all
          applicable laws and regulations. You shall not:
        </p>
        <ul className="list-disc pl-6 text-gray-700 mt-2">
          <li>Upload malicious files or content</li>
          <li>Attempt to bypass any security measures</li>
          <li>
            Use the services to process sensitive or confidential information
          </li>
          <li>Interfere with the proper functioning of the Website</li>
          <li>
            Access the Website through automated means without prior written
            permission
          </li>
        </ul>

        <h3 className="text-xl font-semibold mb-2 mt-4">
          3.2 Data Responsibility
        </h3>
        <p className="text-gray-700">You are solely responsible for:</p>
        <ul className="list-disc pl-6 text-gray-700 mt-2">
          <li>The content and accuracy of files you upload</li>
          <li>Backing up your data before using our tools</li>
          <li>Reviewing the output generated by our tools</li>
          <li>Ensuring you have the right to process the data you upload</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-2">
          4. Privacy and Data Security
        </h2>
        <h3 className="text-xl font-semibold mb-2 mt-4">4.1 Data Processing</h3>
        <ul className="list-disc pl-6 text-gray-700">
          <li>All file processing occurs in your browser</li>
          <li>We do not store or retain any of your uploaded files</li>
          <li>We do not collect or process the content of your JSON files</li>
          <li>Any data transmission is encrypted using HTTPS</li>
        </ul>

        <h3 className="text-xl font-semibold mb-2 mt-4">4.2 Usage Data</h3>
        <p className="text-gray-700">
          We may collect anonymous usage statistics to improve our services,
          including:
        </p>
        <ul className="list-disc pl-6 text-gray-700 mt-2">
          <li>Tool usage frequency</li>
          <li>Browser type</li>
          <li>General geographic location</li>
          <li>Error reports</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-2">
          5. Intellectual Property
        </h2>
        <h3 className="text-xl font-semibold mb-2 mt-4">5.1 Ownership</h3>
        <ul className="list-disc pl-6 text-gray-700">
          <li>
            The Website, including its design, code, and content, is protected
            by copyright and other intellectual property laws
          </li>
          <li>
            The tools' functionality and processing algorithms remain our
            exclusive property
          </li>
          <li>You retain all rights to your uploaded content</li>
        </ul>

        <h3 className="text-xl font-semibold mb-2 mt-4">5.2 Limitations</h3>
        <p className="text-gray-700">You may not:</p>
        <ul className="list-disc pl-6 text-gray-700 mt-2">
          <li>Copy, modify, or distribute our code or content</li>
          <li>Reverse engineer our tools</li>
          <li>Remove any copyright or proprietary notices</li>
          <li>Use our brand name or logos without permission</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-2">
          6. Disclaimer of Warranties
        </h2>
        <p className="text-gray-700">
          THE WEBSITE AND ITS TOOLS ARE PROVIDED "AS IS" AND "AS AVAILABLE"
          WITHOUT ANY WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED,
          INCLUDING BUT NOT LIMITED TO:
        </p>
        <ul className="list-disc pl-6 text-gray-700 mt-2">
          <li>Accuracy of results</li>
          <li>Availability of services</li>
          <li>Fitness for a particular purpose</li>
          <li>Freedom from errors or bugs</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-2">
          7. Limitation of Liability
        </h2>
        <p className="text-gray-700">
          IN NO EVENT SHALL merge-json-files.com BE LIABLE FOR ANY DIRECT,
          INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES ARISING FROM:
        </p>
        <ul className="list-disc pl-6 text-gray-700 mt-2">
          <li>Use or inability to use the Website</li>
          <li>Data loss or corruption</li>
          <li>Errors in processing</li>
          <li>Service interruptions</li>
          <li>Security breaches</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-2">8. Changes to Terms</h2>
        <p className="text-gray-700">
          We reserve the right to modify these Terms of Use at any time. Changes
          will be effective immediately upon posting to the Website. Your
          continued use of the Website after changes constitutes acceptance of
          the modified terms.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-2">9. Termination</h2>
        <p className="text-gray-700">We reserve the right to:</p>
        <ul className="list-disc pl-6 text-gray-700 mt-2">
          <li>
            Terminate or suspend access to our services without prior notice
          </li>
          <li>Remove or disable access to content at our discretion</li>
          <li>Block users who violate these terms</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-2">10. Contact Information</h2>
        <p className="text-gray-700">
          For questions about these Terms of Use, please contact us at{" "}
          <a
            className="text-blue-500 hover:underline"
            href="mailto:jsontools.web@gmail.com"
          >
            jsontools.web@gmail.com
          </a>
          .
        </p>
      </section>

      <section>
        <h2 className="text-2xl font-semibold mb-2">11. Governing Law</h2>
        <p className="text-gray-700">
          These Terms of Use shall be governed by and construed in accordance
          with the laws of the United States, without regard to its conflict of
          law provisions.
        </p>
      </section>
    </div>
  );
};

export default TermsOfUse;
